In [1]:
import pandas as pd

In [2]:
# Load the dataset
climate = pd.read_csv("../../Data/climate-change_mar.csv")
climate.head()

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,#country+name,#country+code,#date+year,#indicator+name,#indicator+code,#indicator+value+num
1,Morocco,MAR,2020,Agricultural land (sq. km),AG.LND.AGRI.K2,303820
2,Morocco,MAR,2019,Agricultural land (sq. km),AG.LND.AGRI.K2,296119.07
3,Morocco,MAR,2018,Agricultural land (sq. km),AG.LND.AGRI.K2,305258.072
4,Morocco,MAR,2017,Agricultural land (sq. km),AG.LND.AGRI.K2,310465.482

In [3]:
# drop the first row
climate = climate.drop(index=0)
# reset the index
climate = climate.reset_index(drop=True)
climate

,Country Name,Country ISO3,Year,Indicator Name,Indicator Code,Value
0,Morocco,MAR,2020,Agricultural land (sq. km),AG.LND.AGRI.K2,303820
1,Morocco,MAR,2019,Agricultural land (sq. km),AG.LND.AGRI.K2,296119.07
2,Morocco,MAR,2018,Agricultural land (sq. km),AG.LND.AGRI.K2,305258.072
3,Morocco,MAR,2017,Agricultural land (sq. km),AG.LND.AGRI.K2,310465.482
4,Morocco,MAR,2016,Agricultural land (sq. km),AG.LND.AGRI.K2,308750
...,...,...,...,...,...,...
2009,Morocco,MAR,1994,"Roads, paved (% of total roads)",IS.ROD.PAVE.ZS,50.2000007629395
2010,Morocco,MAR,1993,"Roads, paved (% of total roads)",IS.ROD.PAVE.ZS,49.5999984741211
2011,Morocco,MAR,1992,"Roads, paved (% of total roads)",IS.ROD.PAVE.ZS,49.5
2012,Morocco,MAR,1991,"Roads, paved (% of total roads)",IS.ROD.PAVE.ZS,49.5
2013,Morocco,MAR,1990,"Roads, paved (% of total roads)",IS.ROD.PAVE.ZS,49.0999984741211

In [4]:
indicators = climate[['Indicator Name','Indicator Code']].copy()
indicators = indicators.astype(str)
indicators.drop_duplicates(inplace=True)
indicators = indicators.reset_index(drop=True)
indicators.to_csv('../../Data/climate-indicators_mapping.csv', index=False)
indicators

                                       Indicator Name     Indicator Code
0                          Agricultural land (sq. km)     AG.LND.AGRI.K2
1                  Agricultural land (% of land area)     AG.LND.AGRI.ZS
2                        Arable land (% of land area)     AG.LND.ARBL.ZS
3   Rural land area where elevation is below 5 met...  AG.LND.EL5M.RU.K2
4   Rural land area where elevation is below 5 met...  AG.LND.EL5M.RU.ZS
..                                                ...                ...
59                                  Population, total        SP.POP.TOTL
60                 Urban population growth (annual %)        SP.URB.GROW
61                                   Urban population        SP.URB.TOTL
62           Urban population (% of total population)  SP.URB.TOTL.IN.ZS
63                    Roads, paved (% of total roads)     IS.ROD.PAVE.ZS

[64 rows x 2 columns]

In [5]:
climate = climate.drop(columns=["Country Name","Country ISO3","Indicator Name"])
climate.head()

   Year  Indicator Code       Value
0  2020  AG.LND.AGRI.K2      303820
1  2019  AG.LND.AGRI.K2   296119.07
2  2018  AG.LND.AGRI.K2  305258.072
3  2017  AG.LND.AGRI.K2  310465.482
4  2016  AG.LND.AGRI.K2      308750

In [6]:
pd.set_option('display.max_columns', None)

In [7]:
# Pivot the dataframe
df_pivot = climate.pivot(index='Year', columns='Indicator Code', values='Value')

# Rename the columns to remove whitespace
df_pivot.columns = df_pivot.columns.str.replace(' ', '_')

# Reset the index
climate = df_pivot.reset_index()

climate.head()

Indicator Code,Year,AG.LND.AGRI.K2,AG.LND.AGRI.ZS,AG.LND.ARBL.ZS,AG.LND.EL5M.RU.K2,AG.LND.EL5M.RU.ZS,AG.LND.EL5M.UR.K2,AG.LND.EL5M.UR.ZS,AG.LND.EL5M.ZS,AG.LND.FRST.K2,AG.LND.FRST.ZS,AG.LND.IRIG.AG.ZS,AG.LND.PRCP.MM,AG.YLD.CREL.KG,BX.KLT.DINV.WD.GD.ZS,EG.ELC.ACCS.ZS,EG.FEC.RNEW.ZS,EN.ATM.CO2E.EG.ZS,EN.ATM.CO2E.GF.KT,EN.ATM.CO2E.GF.ZS,EN.ATM.CO2E.KD.GD,EN.ATM.CO2E.KT,EN.ATM.CO2E.LF.KT,EN.ATM.CO2E.LF.ZS,EN.ATM.CO2E.PC,EN.ATM.CO2E.PP.GD,EN.ATM.CO2E.PP.GD.KD,EN.ATM.CO2E.SF.KT,EN.ATM.CO2E.SF.ZS,EN.ATM.GHGO.KT.CE,EN.ATM.GHGO.ZG,EN.ATM.GHGT.KT.CE,EN.ATM.GHGT.ZG,EN.ATM.HFCG.KT.CE,EN.ATM.METH.KT.CE,EN.ATM.METH.ZG,EN.ATM.NOXE.KT.CE,EN.ATM.NOXE.ZG,EN.ATM.PFCG.KT.CE,EN.ATM.SF6G.KT.CE,EN.CLC.DRSK.XQ,EN.CLC.GHGR.MT.CE,EN.CLC.MDAT.ZS,EN.POP.EL5M.RU.ZS,EN.POP.EL5M.UR.ZS,EN.POP.EL5M.ZS,EN.URB.MCTY.TL.ZS,ER.H2O.FWTL.K3,ER.H2O.FWTL.ZS,ER.LND.PTLD.ZS,ER.MRN.PTMR.ZS,ER.PTD.TOTL.ZS,IC.BUS.EASE.XQ,IS.ROD.PAVE.ZS,NV.AGR.TOTL.ZS,SE.ENR.PRSC.FM.ZS,SE.PRM.CMPT.ZS,SH.DYN.MORT,SH.STA.MALN.ZS,SI.POV.DDAY,SP.POP.GROW,SP.POP.TOTL,SP.URB.GROW,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
0,1960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.335,0.503524672708963,NaN,NaN,2456.89,67.472306143001,NaN,NaN,NaN,876.413,24.0684793554884,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.778794733017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241.8,NaN,NaN,NaN,11769774,NaN,3455253,29.357
1,1961,233700,52.3591880629117,14.7645292826097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346,407.6,NaN,NaN,NaN,NaN,18.335,0.485436893203883,NaN,NaN,2581.568,68.3495145631068,NaN,NaN,NaN,865.412,22.9126213592233,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.0296330495518,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,237,NaN,NaN,2.61582673606549,12081713,4.27785927352892,3606271,29.849
2,1962,235800,52.8296814087915,14.7645292826097,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346,1068.9,NaN,NaN,NaN,NaN,18.335,0.595238095238095,NaN,NaN,1917.841,62.2619047619048,NaN,NaN,NaN,792.072,25.7142857142857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.2857776254706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,232.2,NaN,NaN,2.63870409873429,12404757,4.28674566298687,3764224,30.345
3,1963,238500,53.4346014249227,14.898955952861,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346,891.3,NaN,NaN,NaN,NaN,22.002,0.555555555555555,NaN,NaN,2713.58,68.5185185185185,NaN,NaN,NaN,847.077,21.3888888888889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.5609862614667,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,227.2,NaN,NaN,2.56210206718498,12726686,4.19963251266902,3925674,30.846
4,1964,241100,54.017116996012,15.0109781780705,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,346,864.1,NaN,NaN,NaN,NaN,22.002,0.497512437810945,NaN,NaN,2944.601,66.5837479270315,NaN,NaN,NaN,993.757,22.4709784411277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.8602442117426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222,NaN,NaN,2.464668154362,13044254,4.09494549538208,4089765,31.353

In [8]:
#del climate["Indicator Code"]
#climate = climate.drop(columns='Indicator_Code')
climate.columns

Index(['Year', 'AG.LND.AGRI.K2', 'AG.LND.AGRI.ZS', 'AG.LND.ARBL.ZS',
       'AG.LND.EL5M.RU.K2', 'AG.LND.EL5M.RU.ZS', 'AG.LND.EL5M.UR.K2',
       'AG.LND.EL5M.UR.ZS', 'AG.LND.EL5M.ZS', 'AG.LND.FRST.K2',
       'AG.LND.FRST.ZS', 'AG.LND.IRIG.AG.ZS', 'AG.LND.PRCP.MM',
       'AG.YLD.CREL.KG', 'BX.KLT.DINV.WD.GD.ZS', 'EG.ELC.ACCS.ZS',
       'EG.FEC.RNEW.ZS', 'EN.ATM.CO2E.EG.ZS', 'EN.ATM.CO2E.GF.KT',
       'EN.ATM.CO2E.GF.ZS', 'EN.ATM.CO2E.KD.GD', 'EN.ATM.CO2E.KT',
       'EN.ATM.CO2E.LF.KT', 'EN.ATM.CO2E.LF.ZS', 'EN.ATM.CO2E.PC',
       'EN.ATM.CO2E.PP.GD', 'EN.ATM.CO2E.PP.GD.KD', 'EN.ATM.CO2E.SF.KT',
       'EN.ATM.CO2E.SF.ZS', 'EN.ATM.GHGO.KT.CE', 'EN.ATM.GHGO.ZG',
       'EN.ATM.GHGT.KT.CE', 'EN.ATM.GHGT.ZG', 'EN.ATM.HFCG.KT.CE',
       'EN.ATM.METH.KT.CE', 'EN.ATM.METH.ZG', 'EN.ATM.NOXE.KT.CE',
       'EN.ATM.NOXE.ZG', 'EN.ATM.PFCG.KT.CE', 'EN.ATM.SF6G.KT.CE',
       'EN.CLC.DRSK.XQ', 'EN.CLC.GHGR.MT.CE', 'EN.CLC.MDAT.ZS',
       'EN.POP.EL5M.RU.ZS', 'EN.POP.EL5M.UR.ZS', 'EN.POP.EL5M.ZS',
       'EN.URB.MCTY.TL.ZS', 'ER.H2O.FWTL.K3', 'ER.H2O.FWTL.ZS',
       'ER.LND.PTLD.ZS', 'ER.MRN.PTMR.ZS', 'ER.PTD.TOTL.ZS', 'IC.BUS.EASE.XQ',
       'IS.ROD.PAVE.ZS', 'NV.AGR.TOTL.ZS', 'SE.ENR.PRSC.FM.ZS',
       'SE.PRM.CMPT.ZS', 'SH.DYN.MORT', 'SH.STA.MALN.ZS', 'SI.POV.DDAY',
       'SP.POP.GROW', 'SP.POP.TOTL', 'SP.URB.GROW', 'SP.URB.TOTL',
       'SP.URB.TOTL.IN.ZS'],
      dtype='object', name='Indicator Code')

In [9]:
climate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 65 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  62 non-null     object
 1   AG.LND.AGRI.K2        60 non-null     object
 2   AG.LND.AGRI.ZS        60 non-null     object
 3   AG.LND.ARBL.ZS        60 non-null     object
 4   AG.LND.EL5M.RU.K2     3 non-null      object
 5   AG.LND.EL5M.RU.ZS     3 non-null      object
 6   AG.LND.EL5M.UR.K2     3 non-null      object
 7   AG.LND.EL5M.UR.ZS     3 non-null      object
 8   AG.LND.EL5M.ZS        3 non-null      object
 9   AG.LND.FRST.K2        31 non-null     object
 10  AG.LND.FRST.ZS        31 non-null     object
 11  AG.LND.IRIG.AG.ZS     12 non-null     object
 12  AG.LND.PRCP.MM        59 non-null     object
 13  AG.YLD.CREL.KG        60 non-null     object
 14  BX.KLT.DINV.WD.GD.ZS  52 non-null     object
 15  EG.ELC.ACCS.ZS        29 non-null     object
 16  EG.FEC.RNEW.ZS        30 non-null     object
 17  EN.ATM.CO2E.EG.ZS     44 non-null     object
 18  EN.ATM.CO2E.GF.KT     57 non-null     object
 19  EN.ATM.CO2E.GF.ZS     57 non-null     object
 20  EN.ATM.CO2E.KD.GD     30 non-null     object
 21  EN.ATM.CO2E.KT        30 non-null     object
 22  EN.ATM.CO2E.LF.KT     57 non-null     object
 23  EN.ATM.CO2E.LF.ZS     57 non-null     object
 24  EN.ATM.CO2E.PC        30 non-null     object
 25  EN.ATM.CO2E.PP.GD     30 non-null     object
 26  EN.ATM.CO2E.PP.GD.KD  30 non-null     object
 27  EN.ATM.CO2E.SF.KT     57 non-null     object
 28  EN.ATM.CO2E.SF.ZS     57 non-null     object
 29  EN.ATM.GHGO.KT.CE     47 non-null     object
 30  EN.ATM.GHGO.ZG        22 non-null     object
 31  EN.ATM.GHGT.KT.CE     30 non-null     object
 32  EN.ATM.GHGT.ZG        22 non-null     object
 33  EN.ATM.HFCG.KT.CE     5 non-null      object
 34  EN.ATM.METH.KT.CE     30 non-null     object
 35  EN.ATM.METH.ZG        22 non-null     object
 36  EN.ATM.NOXE.KT.CE     30 non-null     object
 37  EN.ATM.NOXE.ZG        22 non-null     object
 38  EN.ATM.PFCG.KT.CE     5 non-null      object
 39  EN.ATM.SF6G.KT.CE     5 non-null      object
 40  EN.CLC.DRSK.XQ        1 non-null      object
 41  EN.CLC.GHGR.MT.CE     1 non-null      object
 42  EN.CLC.MDAT.ZS        1 non-null      object
 43  EN.POP.EL5M.RU.ZS     3 non-null      object
 44  EN.POP.EL5M.UR.ZS     3 non-null      object
 45  EN.POP.EL5M.ZS        3 non-null      object
 46  EN.URB.MCTY.TL.ZS     62 non-null     object
 47  ER.H2O.FWTL.K3        45 non-null     object
 48  ER.H2O.FWTL.ZS        45 non-null     object
 49  ER.LND.PTLD.ZS        6 non-null      object
 50  ER.MRN.PTMR.ZS        6 non-null      object
 51  ER.PTD.TOTL.ZS        6 non-null      object
 52  IC.BUS.EASE.XQ        1 non-null      object
 53  IS.ROD.PAVE.ZS        21 non-null     object
 54  NV.AGR.TOTL.ZS        57 non-null     object
 55  SE.ENR.PRSC.FM.ZS     46 non-null     object
 56  SE.PRM.CMPT.ZS        51 non-null     object
 57  SH.DYN.MORT           61 non-null     object
 58  SH.STA.MALN.ZS        6 non-null      object
 59  SI.POV.DDAY           6 non-null      object
 60  SP.POP.GROW           61 non-null     object
 61  SP.POP.TOTL           62 non-null     object
 62  SP.URB.GROW           61 non-null     object
 63  SP.URB.TOTL           62 non-null     object
 64  SP.URB.TOTL.IN.ZS     62 non-null     object
dtypes: object(65)
memory usage: 31.6+ KB

In [10]:
# Change the data type of all columns except "Year" to float
climate[climate.columns.difference(['Year'])] = climate[climate.columns.difference(['Year'])].astype(float)

# Change the data type of "Year" column to int
climate['Year'] = climate['Year'].astype(int)

climate.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 65 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  62 non-null     int32
 1   AG.LND.AGRI.K2        60 non-null     float64
 2   AG.LND.AGRI.ZS        60 non-null     float64
 3   AG.LND.ARBL.ZS        60 non-null     float64
 4   AG.LND.EL5M.RU.K2     3 non-null      float64
 5   AG.LND.EL5M.RU.ZS     3 non-null      float64
 6   AG.LND.EL5M.UR.K2     3 non-null      float64
 7   AG.LND.EL5M.UR.ZS     3 non-null      float64
 8   AG.LND.EL5M.ZS        3 non-null      float64
 9   AG.LND.FRST.K2        31 non-null     float64
 10  AG.LND.FRST.ZS        31 non-null     float64
 11  AG.LND.IRIG.AG.ZS     12 non-null     float64
 12  AG.LND.PRCP.MM        59 non-null     float64
 13  AG.YLD.CREL.KG        60 non-null     float64
 14  BX.KLT.DINV.WD.GD.ZS  52 non-null     float64
 15  EG.ELC.ACCS.ZS        29 non-null     float64
 16  EG.FEC.RNEW.ZS        30 non-null     float64
 17  EN.ATM.CO2E.EG.ZS     44 non-null     float64
 18  EN.ATM.CO2E.GF.KT     57 non-null     float64
 19  EN.ATM.CO2E.GF.ZS     57 non-null     float64
 20  EN.ATM.CO2E.KD.GD     30 non-null     float64
 21  EN.ATM.CO2E.KT        30 non-null     float64
 22  EN.ATM.CO2E.LF.KT     57 non-null     float64
 23  EN.ATM.CO2E.LF.ZS     57 non-null     float64
 24  EN.ATM.CO2E.PC        30 non-null     float64
 25  EN.ATM.CO2E.PP.GD     30 non-null     float64
 26  EN.ATM.CO2E.PP.GD.KD  30 non-null     float64
 27  EN.ATM.CO2E.SF.KT     57 non-null     float64
 28  EN.ATM.CO2E.SF.ZS     57 non-null     float64
 29  EN.ATM.GHGO.KT.CE     47 non-null     float64
 30  EN.ATM.GHGO.ZG        22 non-null     float64
 31  EN.ATM.GHGT.KT.CE     30 non-null     float64
 32  EN.ATM.GHGT.ZG        22 non-null     float64
 33  EN.ATM.HFCG.KT.CE     5 non-null      float64
 34  EN.ATM.METH.KT.CE     30 non-null     float64
 35  EN.ATM.METH.ZG        22 non-null     float64
 36  EN.ATM.NOXE.KT.CE     30 non-null     float64
 37  EN.ATM.NOXE.ZG        22 non-null     float64
 38  EN.ATM.PFCG.KT.CE     5 non-null      float64
 39  EN.ATM.SF6G.KT.CE     5 non-null      float64
 40  EN.CLC.DRSK.XQ        1 non-null      float64
 41  EN.CLC.GHGR.MT.CE     1 non-null      float64
 42  EN.CLC.MDAT.ZS        1 non-null      float64
 43  EN.POP.EL5M.RU.ZS     3 non-null      float64
 44  EN.POP.EL5M.UR.ZS     3 non-null      float64
 45  EN.POP.EL5M.ZS        3 non-null      float64
 46  EN.URB.MCTY.TL.ZS     62 non-null     float64
 47  ER.H2O.FWTL.K3        45 non-null     float64
 48  ER.H2O.FWTL.ZS        45 non-null     float64
 49  ER.LND.PTLD.ZS        6 non-null      float64
 50  ER.MRN.PTMR.ZS        6 non-null      float64
 51  ER.PTD.TOTL.ZS        6 non-null      float64
 52  IC.BUS.EASE.XQ        1 non-null      float64
 53  IS.ROD.PAVE.ZS        21 non-null     float64
 54  NV.AGR.TOTL.ZS        57 non-null     float64
 55  SE.ENR.PRSC.FM.ZS     46 non-null     float64
 56  SE.PRM.CMPT.ZS        51 non-null     float64
 57  SH.DYN.MORT           61 non-null     float64
 58  SH.STA.MALN.ZS        6 non-null      float64
 59  SI.POV.DDAY           6 non-null      float64
 60  SP.POP.GROW           61 non-null     float64
 61  SP.POP.TOTL           62 non-null     float64
 62  SP.URB.GROW           61 non-null     float64
 63  SP.URB.TOTL           62 non-null     float64
 64  SP.URB.TOTL.IN.ZS     62 non-null     float64
dtypes: float64(64), int32(1)
memory usage: 31.4 KB

In [11]:
climate.Year.unique()

array([1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970,
       1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981,
       1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992,
       1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003,
       2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014,
       2015, 2016, 2017, 2018, 2019, 2020, 2021])

In [12]:
sum(climate.Year.duplicated())

0

In [13]:
climate = climate[(climate['Year'] >= 2011) & (climate['Year'] <= 2020)]
print(climate.Year.unique())
climate

[2011 2012 2013 2014 2015 2016 2017 2018 2019 2020]

Indicator Code,Year,AG.LND.AGRI.K2,AG.LND.AGRI.ZS,AG.LND.ARBL.ZS,AG.LND.EL5M.RU.K2,AG.LND.EL5M.RU.ZS,AG.LND.EL5M.UR.K2,AG.LND.EL5M.UR.ZS,AG.LND.EL5M.ZS,AG.LND.FRST.K2,AG.LND.FRST.ZS,AG.LND.IRIG.AG.ZS,AG.LND.PRCP.MM,AG.YLD.CREL.KG,BX.KLT.DINV.WD.GD.ZS,EG.ELC.ACCS.ZS,EG.FEC.RNEW.ZS,EN.ATM.CO2E.EG.ZS,EN.ATM.CO2E.GF.KT,EN.ATM.CO2E.GF.ZS,EN.ATM.CO2E.KD.GD,EN.ATM.CO2E.KT,EN.ATM.CO2E.LF.KT,EN.ATM.CO2E.LF.ZS,EN.ATM.CO2E.PC,EN.ATM.CO2E.PP.GD,EN.ATM.CO2E.PP.GD.KD,EN.ATM.CO2E.SF.KT,EN.ATM.CO2E.SF.ZS,EN.ATM.GHGO.KT.CE,EN.ATM.GHGO.ZG,EN.ATM.GHGT.KT.CE,EN.ATM.GHGT.ZG,EN.ATM.HFCG.KT.CE,EN.ATM.METH.KT.CE,EN.ATM.METH.ZG,EN.ATM.NOXE.KT.CE,EN.ATM.NOXE.ZG,EN.ATM.PFCG.KT.CE,EN.ATM.SF6G.KT.CE,EN.CLC.DRSK.XQ,EN.CLC.GHGR.MT.CE,EN.CLC.MDAT.ZS,EN.POP.EL5M.RU.ZS,EN.POP.EL5M.UR.ZS,EN.POP.EL5M.ZS,EN.URB.MCTY.TL.ZS,ER.H2O.FWTL.K3,ER.H2O.FWTL.ZS,ER.LND.PTLD.ZS,ER.MRN.PTMR.ZS,ER.PTD.TOTL.ZS,IC.BUS.EASE.XQ,IS.ROD.PAVE.ZS,NV.AGR.TOTL.ZS,SE.ENR.PRSC.FM.ZS,SE.PRM.CMPT.ZS,SH.DYN.MORT,SH.STA.MALN.ZS,SI.POV.DDAY,SP.POP.GROW,SP.POP.TOTL,SP.URB.GROW,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
51,2011,301038.000,67.451938,17.485548,NaN,NaN,NaN,NaN,NaN,56765.94,12.719234,4.605731,346.0,1614.4,2.487275,93.446434,11.88,3.139987,1639.149,2.836389,0.677687,55939.998627,36603.994,63.339668,1.700113,0.250497,0.276731,11474.043,19.854721,3425.379883,-10.826286,75750.000000,108.776188,NaN,11010.000229,28.954738,8440.0,4.355022,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,21.648299,10.573,36.458621,NaN,NaN,NaN,NaN,NaN,13.119988,0.91374,89.361572,29.5,2.9,NaN,1.342666,32903699.0,2.308378,19275316.0,58.581
52,2012,304030.000,68.122339,18.030473,NaN,NaN,NaN,NaN,NaN,56786.18,12.723769,NaN,346.0,1016.6,2.892094,94.210518,10.93,3.222693,2398.218,3.987062,0.683052,58080.001831,37286.056,61.988456,1.741416,0.256850,0.278922,11470.376,19.069619,4960.088379,-10.826286,77550.003052,114.250713,NaN,11100.000381,30.231518,8000.0,5.388240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.642350,10.573,36.458621,NaN,NaN,NaN,NaN,NaN,12.329560,0.91295,98.019630,27.8,NaN,NaN,1.353772,33352169.0,2.306865,19725140.0,59.142
53,2013,305850.000,68.530137,18.211965,NaN,NaN,NaN,NaN,NaN,56806.42,12.728304,NaN,346.0,1828.3,3.146164,97.199997,11.59,3.186117,2350.547,3.935946,0.647904,57590.000153,37003.697,61.961984,1.703668,0.243335,0.264570,11221.020,18.789384,5369.218750,NaN,78040.000916,NaN,NaN,11289.999962,NaN,8770.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.639547,10.573,36.458621,NaN,NaN,NaN,NaN,NaN,13.389567,NaN,96.023102,26.3,NaN,1.4,1.344234,33803527.0,2.283304,20180706.0,59.700
54,2014,300825.000,67.404212,17.031369,NaN,NaN,NaN,NaN,NaN,56826.66,12.732839,NaN,346.0,1454.3,2.959241,91.599998,11.14,3.222090,2247.871,3.675394,0.554636,58689.998627,34488.135,56.390018,1.713646,0.236404,0.226484,15313.392,25.038247,4386.330566,NaN,79239.997864,NaN,NaN,11479.999542,NaN,8670.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.646865,10.573,36.458621,NaN,NaN,NaN,NaN,NaN,10.353147,NaN,96.308159,24.9,NaN,NaN,1.308063,34248603.0,2.235073,20636838.0,60.256
55,2015,300470.000,67.324670,16.798790,738.700065,0.178371,156.332514,0.037749,0.21612,56846.90,12.737374,NaN,346.0,2140.7,2.946097,97.300003,11.25,NaN,2324.878,3.681517,0.547121,60409.999847,34106.767,54.009132,1.741903,0.223932,0.223415,16857.199,26.693902,6184.521973,NaN,81459.999084,NaN,NaN,11550.000191,NaN,9090.0,NaN,NaN,NaN,NaN,NaN,NaN,0.278145,1.169118,1.447262,21.668047,10.573,36.458621,NaN,NaN,NaN,NaN,NaN,11.796193,NaN,96.257713,23.5,NaN,NaN,1.253058,34680458.0,2.166626,21088840.0,60.809
56,2016,308750.000,69.179924,18.420345,NaN,NaN,NaN,NaN,NaN,56997.90,12.771208,5.416356,346.0,936.0,1.930010,97.800003,11.06,NaN,2365.215,3.749548,0.543473,60319.999695,34682.486,54.981747,1.718163,0.220170,0.221926,16248.477,25.758524,5825.536133,NaN,80260.002136,NaN,NaN,11670.000076,NaN,7830.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.697709,10.573,36.458621,30.810000,0.460642,18.546366,NaN,NaN,10.321965,NaN,95.042038,22.3,NaN,NaN,1.223170,35107264.0,2.125203,21541817.0,61.360
57,2017,310465.482,69.564302,18.863453,NaN,NaN,NaN,NaN,NaN,57115.90,12.797647,5.709169,346.0,1757.6,2.260922,100.000000,10.45,NaN,NaN,NaN,0.544752,63520.000458,NaN,NaN,1.787880,0.222448,0.222448,NaN,NaN,NaN,NaN,84989.997864,NaN,NaN,11770.000458,NaN,9210.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.736284,10.573,36.458621,30.777601,0.259984,18.446888,NaN,NaN,11.160289,0.93019,92.929527,21.2,2.6,NaN,1.191629,35528115.0,2.080754,21994745.0,61.908
58,2018,305258.072,68.397507,17.593931,NaN,NaN,NaN,NaN,NaN,57215.90,12.820054,5.586093,346.0,2263.6,2.783379,98.099998,10.90,NaN,NaN,NaN,0.540531,64959.999084,NaN,NaN,1.808085,0.215574,0.220724,NaN,NaN,NaN,NaN,86809.997559,NaN,NaN,11970.000267,NaN,9370.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.793043,10.573,36.458621,30.777601,0.259984,18.446888,NaN,NaN,11.305540,0.94147,93.597458,20.3,NaN,NaN,1.117897,35927511.0,1.994383,22437808.0,62.453
59,2019,296119.070,66.349780,15.458131,NaN,NaN,NaN,NaN,NaN,57320.90,12.843581,5.958752,346.0,1454.1,1.334801,99.599998,10.69,NaN,NaN,NaN,0.578071,71480.003357,NaN,NaN,1.968907,0.226494,0.236054,NaN,NaN,NaN,NaN,93080.001831,NaN,NaN,12159.999847,NaN,8890.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.874308,10.573,36.458621,30.777600,0.259984,18.446877,53.0,NaN,10.842402,0.95111,97.135727,19.5,NaN,NaN,1.043584,36304408.0,1.906108,22869599.0,62.994
60,2020,303820.000,68.075286,17.138696,NaN,NaN,NaN,NaN,NaN,57424.90,12.866883,NaN,NaN,742.9,1.169126,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.966290,NaN,NaN,4.267908,0.689612,2.822088,NaN,NaN,10.664177,0.96221,100.088120,18.7,NaN,NaN,1.053160,36688772.0,1.903584,23309111.0,63.532

In [14]:
duplicates = climate.duplicated()
print("Number of duplicated rows:", duplicates.sum())

Number of duplicated rows: 0

In [15]:
low_count_columns = climate.columns[climate.count() < 7]
low_count_columns

Index(['AG.LND.EL5M.RU.K2', 'AG.LND.EL5M.RU.ZS', 'AG.LND.EL5M.UR.K2',
       'AG.LND.EL5M.UR.ZS', 'AG.LND.EL5M.ZS', 'AG.LND.IRIG.AG.ZS',
       'EN.ATM.CO2E.EG.ZS', 'EN.ATM.CO2E.GF.KT', 'EN.ATM.CO2E.GF.ZS',
       'EN.ATM.CO2E.LF.KT', 'EN.ATM.CO2E.LF.ZS', 'EN.ATM.CO2E.SF.KT',
       'EN.ATM.CO2E.SF.ZS', 'EN.ATM.GHGO.KT.CE', 'EN.ATM.GHGO.ZG',
       'EN.ATM.GHGT.ZG', 'EN.ATM.HFCG.KT.CE', 'EN.ATM.METH.ZG',
       'EN.ATM.NOXE.ZG', 'EN.ATM.PFCG.KT.CE', 'EN.ATM.SF6G.KT.CE',
       'EN.CLC.DRSK.XQ', 'EN.CLC.GHGR.MT.CE', 'EN.CLC.MDAT.ZS',
       'EN.POP.EL5M.RU.ZS', 'EN.POP.EL5M.UR.ZS', 'EN.POP.EL5M.ZS',
       'ER.LND.PTLD.ZS', 'ER.MRN.PTMR.ZS', 'ER.PTD.TOTL.ZS', 'IC.BUS.EASE.XQ',
       'IS.ROD.PAVE.ZS', 'SE.ENR.PRSC.FM.ZS', 'SH.STA.MALN.ZS', 'SI.POV.DDAY'],
      dtype='object', name='Indicator Code')

In [16]:
low_count_indicators = indicators.loc[indicators['Indicator Code'].isin(low_count_columns)]
print("Number of the indicators that need to be deleted:",low_count_indicators['Indicator Name'].drop_duplicates().count())
low_count_indicators.drop_duplicates()

Number of the indicators that need to be deleted: 35

                                       Indicator Name     Indicator Code
3   Rural land area where elevation is below 5 met...  AG.LND.EL5M.RU.K2
4   Rural land area where elevation is below 5 met...  AG.LND.EL5M.RU.ZS
5   Urban land area where elevation is below 5 met...  AG.LND.EL5M.UR.K2
6   Urban land area where elevation is below 5 met...  AG.LND.EL5M.UR.ZS
7   Land area where elevation is below 5 meters (%...     AG.LND.EL5M.ZS
10  Agricultural irrigated land (% of total agricu...  AG.LND.IRIG.AG.ZS
16  CO2 intensity (kg per kg of oil equivalent ene...  EN.ATM.CO2E.EG.ZS
17   CO2 emissions from gaseous fuel consumption (kt)  EN.ATM.CO2E.GF.KT
18  CO2 emissions from gaseous fuel consumption (%...  EN.ATM.CO2E.GF.ZS
21    CO2 emissions from liquid fuel consumption (kt)  EN.ATM.CO2E.LF.KT
22  CO2 emissions from liquid fuel consumption (% ...  EN.ATM.CO2E.LF.ZS
26     CO2 emissions from solid fuel consumption (kt)  EN.ATM.CO2E.SF.KT
27  CO2 emissions from solid fuel consumption (% o...  EN.ATM.CO2E.SF.ZS
28  Other greenhouse gas emissions, HFC, PFC and S...  EN.ATM.GHGO.KT.CE
29  Other greenhouse gas emissions (% change from ...     EN.ATM.GHGO.ZG
31  Total greenhouse gas emissions (% change from ...     EN.ATM.GHGT.ZG
32  HFC gas emissions (thousand metric tons of CO2...  EN.ATM.HFCG.KT.CE
34             Methane emissions (% change from 1990)     EN.ATM.METH.ZG
36       Nitrous oxide emissions (% change from 1990)     EN.ATM.NOXE.ZG
37  PFC gas emissions (thousand metric tons of CO2...  EN.ATM.PFCG.KT.CE
38  SF6 gas emissions (thousand metric tons of CO2...  EN.ATM.SF6G.KT.CE
39  Disaster risk reduction progress score (1-5 sc...     EN.CLC.DRSK.XQ
40  GHG net emissions/removals by LUCF (Mt of CO2 ...  EN.CLC.GHGR.MT.CE
41  Droughts, floods, extreme temperatures (% of p...     EN.CLC.MDAT.ZS
42  Rural population living in areas where elevati...  EN.POP.EL5M.RU.ZS
43  Urban population living in areas where elevati...  EN.POP.EL5M.UR.ZS
44  Population living in areas where elevation is ...     EN.POP.EL5M.ZS
48  Terrestrial protected areas (% of total land a...     ER.LND.PTLD.ZS
49   Marine protected areas (% of territorial waters)     ER.MRN.PTMR.ZS
50  Terrestrial and marine protected areas (% of t...     ER.PTD.TOTL.ZS
51  Ease of doing business rank (1=most business-f...     IC.BUS.EASE.XQ
53  School enrollment, primary and secondary (gros...  SE.ENR.PRSC.FM.ZS
56  Prevalence of underweight, weight for age (% o...     SH.STA.MALN.ZS
57  Poverty headcount ratio at $2.15 a day (2017 P...        SI.POV.DDAY
63                    Roads, paved (% of total roads)     IS.ROD.PAVE.ZS

In [17]:
climate = climate.drop(columns=low_count_columns)

In [18]:
climate.shape

(10, 30)

In [19]:
climate.describe()

Indicator Code,Year,AG.LND.AGRI.K2,AG.LND.AGRI.ZS,AG.LND.ARBL.ZS,AG.LND.FRST.K2,AG.LND.FRST.ZS,AG.LND.PRCP.MM,AG.YLD.CREL.KG,BX.KLT.DINV.WD.GD.ZS,EG.ELC.ACCS.ZS,EG.FEC.RNEW.ZS,EN.ATM.CO2E.KD.GD,EN.ATM.CO2E.KT,EN.ATM.CO2E.PC,EN.ATM.CO2E.PP.GD,EN.ATM.CO2E.PP.GD.KD,EN.ATM.GHGT.KT.CE,EN.ATM.METH.KT.CE,EN.ATM.NOXE.KT.CE,EN.URB.MCTY.TL.ZS,ER.H2O.FWTL.K3,ER.H2O.FWTL.ZS,NV.AGR.TOTL.ZS,SE.PRM.CMPT.ZS,SH.DYN.MORT,SP.POP.GROW,SP.POP.TOTL,SP.URB.GROW,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,9.0,10.000000,10.000000,10.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,10.000000,9.000,9.000000,10.000000,10.000000,10.000000,10.000000,1.000000e+01,10.000000,1.000000e+01,10.000000
mean,2015.50000,303662.562400,68.040010,17.503270,57010.760000,12.774089,346.0,1520.850000,2.390911,96.925695,11.098889,0.590803,61221.111298,1.764865,0.232856,0.241253,81908.888923,11555.555662,8696.666667,21.731274,10.573,36.458621,11.528283,95.476305,23.400000,1.223123,3.485445e+07,2.131028,2.130599e+07,61.073500
std,3.02765,4238.564851,0.949712,0.972645,243.555089,0.054572,0.0,506.143096,0.703451,2.910781,0.437848,0.060813,4787.054975,0.085037,0.014566,0.024833,5480.091972,383.670100,526.474121,0.113033,0.000,0.000000,1.103027,2.975591,3.654525,0.118942,1.278035e+06,0.156775,1.360240e+06,1.666068
min,2011.00000,296119.070000,66.349780,15.458131,56765.940000,12.719234,346.0,742.900000,1.169126,91.599998,10.450000,0.540531,55939.998627,1.700113,0.215574,0.220724,75750.000000,11010.000229,7830.000000,21.639547,10.573,36.458621,10.321965,89.361572,18.700000,1.043584,3.290370e+07,1.903584,1.927532e+07,58.581000
25%,2013.25000,300878.250000,67.416144,17.058201,56811.480000,12.729438,346.0,1125.975000,2.012738,94.957888,10.900000,0.544752,58080.001831,1.713646,0.222448,0.222448,78040.000916,11289.999962,8440.000000,21.647224,10.573,36.458621,10.708733,93.958603,20.525000,1.136330,3.391480e+07,2.015976,2.029474e+07,59.839000
50%,2015.50000,303925.000000,68.098812,17.539739,56922.400000,12.754291,346.0,1534.350000,2.635327,97.550003,11.060000,0.554636,60319.999695,1.741416,0.226494,0.226484,80260.002136,11550.000191,8770.000000,21.682878,10.573,36.458621,11.232915,96.140408,22.900000,1.238114,3.489386e+07,2.145915,2.131533e+07,61.084500
75%,2017.75000,305702.018000,68.496979,18.166592,57190.900000,12.814452,346.0,1810.625000,2.932596,99.224998,11.250000,0.647904,63520.000458,1.787880,0.243335,0.264570,84989.997864,11770.000458,9090.000000,21.778853,10.573,36.458621,12.196219,96.928835,25.950000,1.334015,3.582766e+07,2.271246,2.232704e+07,62.316750
max,2020.00000,310465.482000,69.564302,18.863453,57424.900000,12.866883,346.0,2263.600000,3.146164,100.000000,11.880000,0.683052,71480.003357,1.968907,0.256850,0.278922,93080.001831,12159.999847,9370.000000,21.966290,10.573,36.458621,13.389567,100.088120,29.500000,1.353772,3.668877e+07,2.308378,2.330911e+07,63.532000

In [20]:
climate

Indicator Code,Year,AG.LND.AGRI.K2,AG.LND.AGRI.ZS,AG.LND.ARBL.ZS,AG.LND.FRST.K2,AG.LND.FRST.ZS,AG.LND.PRCP.MM,AG.YLD.CREL.KG,BX.KLT.DINV.WD.GD.ZS,EG.ELC.ACCS.ZS,EG.FEC.RNEW.ZS,EN.ATM.CO2E.KD.GD,EN.ATM.CO2E.KT,EN.ATM.CO2E.PC,EN.ATM.CO2E.PP.GD,EN.ATM.CO2E.PP.GD.KD,EN.ATM.GHGT.KT.CE,EN.ATM.METH.KT.CE,EN.ATM.NOXE.KT.CE,EN.URB.MCTY.TL.ZS,ER.H2O.FWTL.K3,ER.H2O.FWTL.ZS,NV.AGR.TOTL.ZS,SE.PRM.CMPT.ZS,SH.DYN.MORT,SP.POP.GROW,SP.POP.TOTL,SP.URB.GROW,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
51,2011,301038.000,67.451938,17.485548,56765.94,12.719234,346.0,1614.4,2.487275,93.446434,11.88,0.677687,55939.998627,1.700113,0.250497,0.276731,75750.000000,11010.000229,8440.0,21.648299,10.573,36.458621,13.119988,89.361572,29.5,1.342666,32903699.0,2.308378,19275316.0,58.581
52,2012,304030.000,68.122339,18.030473,56786.18,12.723769,346.0,1016.6,2.892094,94.210518,10.93,0.683052,58080.001831,1.741416,0.256850,0.278922,77550.003052,11100.000381,8000.0,21.642350,10.573,36.458621,12.329560,98.019630,27.8,1.353772,33352169.0,2.306865,19725140.0,59.142
53,2013,305850.000,68.530137,18.211965,56806.42,12.728304,346.0,1828.3,3.146164,97.199997,11.59,0.647904,57590.000153,1.703668,0.243335,0.264570,78040.000916,11289.999962,8770.0,21.639547,10.573,36.458621,13.389567,96.023102,26.3,1.344234,33803527.0,2.283304,20180706.0,59.700
54,2014,300825.000,67.404212,17.031369,56826.66,12.732839,346.0,1454.3,2.959241,91.599998,11.14,0.554636,58689.998627,1.713646,0.236404,0.226484,79239.997864,11479.999542,8670.0,21.646865,10.573,36.458621,10.353147,96.308159,24.9,1.308063,34248603.0,2.235073,20636838.0,60.256
55,2015,300470.000,67.324670,16.798790,56846.90,12.737374,346.0,2140.7,2.946097,97.300003,11.25,0.547121,60409.999847,1.741903,0.223932,0.223415,81459.999084,11550.000191,9090.0,21.668047,10.573,36.458621,11.796193,96.257713,23.5,1.253058,34680458.0,2.166626,21088840.0,60.809
56,2016,308750.000,69.179924,18.420345,56997.90,12.771208,346.0,936.0,1.930010,97.800003,11.06,0.543473,60319.999695,1.718163,0.220170,0.221926,80260.002136,11670.000076,7830.0,21.697709,10.573,36.458621,10.321965,95.042038,22.3,1.223170,35107264.0,2.125203,21541817.0,61.360
57,2017,310465.482,69.564302,18.863453,57115.90,12.797647,346.0,1757.6,2.260922,100.000000,10.45,0.544752,63520.000458,1.787880,0.222448,0.222448,84989.997864,11770.000458,9210.0,21.736284,10.573,36.458621,11.160289,92.929527,21.2,1.191629,35528115.0,2.080754,21994745.0,61.908
58,2018,305258.072,68.397507,17.593931,57215.90,12.820054,346.0,2263.6,2.783379,98.099998,10.90,0.540531,64959.999084,1.808085,0.215574,0.220724,86809.997559,11970.000267,9370.0,21.793043,10.573,36.458621,11.305540,93.597458,20.3,1.117897,35927511.0,1.994383,22437808.0,62.453
59,2019,296119.070,66.349780,15.458131,57320.90,12.843581,346.0,1454.1,1.334801,99.599998,10.69,0.578071,71480.003357,1.968907,0.226494,0.236054,93080.001831,12159.999847,8890.0,21.874308,10.573,36.458621,10.842402,97.135727,19.5,1.043584,36304408.0,1.906108,22869599.0,62.994
60,2020,303820.000,68.075286,17.138696,57424.90,12.866883,NaN,742.9,1.169126,100.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.966290,NaN,NaN,10.664177,100.088120,18.7,1.053160,36688772.0,1.903584,23309111.0,63.532

In [21]:
# Replace NaN values with column mean
climate.fillna(climate.mean(), inplace=True)

In [22]:
climate

Indicator Code,Year,AG.LND.AGRI.K2,AG.LND.AGRI.ZS,AG.LND.ARBL.ZS,AG.LND.FRST.K2,AG.LND.FRST.ZS,AG.LND.PRCP.MM,AG.YLD.CREL.KG,BX.KLT.DINV.WD.GD.ZS,EG.ELC.ACCS.ZS,EG.FEC.RNEW.ZS,EN.ATM.CO2E.KD.GD,EN.ATM.CO2E.KT,EN.ATM.CO2E.PC,EN.ATM.CO2E.PP.GD,EN.ATM.CO2E.PP.GD.KD,EN.ATM.GHGT.KT.CE,EN.ATM.METH.KT.CE,EN.ATM.NOXE.KT.CE,EN.URB.MCTY.TL.ZS,ER.H2O.FWTL.K3,ER.H2O.FWTL.ZS,NV.AGR.TOTL.ZS,SE.PRM.CMPT.ZS,SH.DYN.MORT,SP.POP.GROW,SP.POP.TOTL,SP.URB.GROW,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
51,2011,301038.000,67.451938,17.485548,56765.94,12.719234,346.0,1614.4,2.487275,93.446434,11.880000,0.677687,55939.998627,1.700113,0.250497,0.276731,75750.000000,11010.000229,8440.000000,21.648299,10.573,36.458621,13.119988,89.361572,29.5,1.342666,32903699.0,2.308378,19275316.0,58.581
52,2012,304030.000,68.122339,18.030473,56786.18,12.723769,346.0,1016.6,2.892094,94.210518,10.930000,0.683052,58080.001831,1.741416,0.256850,0.278922,77550.003052,11100.000381,8000.000000,21.642350,10.573,36.458621,12.329560,98.019630,27.8,1.353772,33352169.0,2.306865,19725140.0,59.142
53,2013,305850.000,68.530137,18.211965,56806.42,12.728304,346.0,1828.3,3.146164,97.199997,11.590000,0.647904,57590.000153,1.703668,0.243335,0.264570,78040.000916,11289.999962,8770.000000,21.639547,10.573,36.458621,13.389567,96.023102,26.3,1.344234,33803527.0,2.283304,20180706.0,59.700
54,2014,300825.000,67.404212,17.031369,56826.66,12.732839,346.0,1454.3,2.959241,91.599998,11.140000,0.554636,58689.998627,1.713646,0.236404,0.226484,79239.997864,11479.999542,8670.000000,21.646865,10.573,36.458621,10.353147,96.308159,24.9,1.308063,34248603.0,2.235073,20636838.0,60.256
55,2015,300470.000,67.324670,16.798790,56846.90,12.737374,346.0,2140.7,2.946097,97.300003,11.250000,0.547121,60409.999847,1.741903,0.223932,0.223415,81459.999084,11550.000191,9090.000000,21.668047,10.573,36.458621,11.796193,96.257713,23.5,1.253058,34680458.0,2.166626,21088840.0,60.809
56,2016,308750.000,69.179924,18.420345,56997.90,12.771208,346.0,936.0,1.930010,97.800003,11.060000,0.543473,60319.999695,1.718163,0.220170,0.221926,80260.002136,11670.000076,7830.000000,21.697709,10.573,36.458621,10.321965,95.042038,22.3,1.223170,35107264.0,2.125203,21541817.0,61.360
57,2017,310465.482,69.564302,18.863453,57115.90,12.797647,346.0,1757.6,2.260922,100.000000,10.450000,0.544752,63520.000458,1.787880,0.222448,0.222448,84989.997864,11770.000458,9210.000000,21.736284,10.573,36.458621,11.160289,92.929527,21.2,1.191629,35528115.0,2.080754,21994745.0,61.908
58,2018,305258.072,68.397507,17.593931,57215.90,12.820054,346.0,2263.6,2.783379,98.099998,10.900000,0.540531,64959.999084,1.808085,0.215574,0.220724,86809.997559,11970.000267,9370.000000,21.793043,10.573,36.458621,11.305540,93.597458,20.3,1.117897,35927511.0,1.994383,22437808.0,62.453
59,2019,296119.070,66.349780,15.458131,57320.90,12.843581,346.0,1454.1,1.334801,99.599998,10.690000,0.578071,71480.003357,1.968907,0.226494,0.236054,93080.001831,12159.999847,8890.000000,21.874308,10.573,36.458621,10.842402,97.135727,19.5,1.043584,36304408.0,1.906108,22869599.0,62.994
60,2020,303820.000,68.075286,17.138696,57424.90,12.866883,346.0,742.9,1.169126,100.000000,11.098889,0.590803,61221.111298,1.764865,0.232856,0.241253,81908.888923,11555.555662,8696.666667,21.966290,10.573,36.458621,10.664177,100.088120,18.7,1.053160,36688772.0,1.903584,23309111.0,63.532

In [23]:
same_val_cols = [col for col in climate.columns if climate[col].nunique() == 1]
print(same_val_cols)
climate = climate.drop(same_val_cols, axis=1)

['AG.LND.PRCP.MM', 'ER.H2O.FWTL.K3', 'ER.H2O.FWTL.ZS']

In [24]:
climate

Indicator Code,Year,AG.LND.AGRI.K2,AG.LND.AGRI.ZS,AG.LND.ARBL.ZS,AG.LND.FRST.K2,AG.LND.FRST.ZS,AG.YLD.CREL.KG,BX.KLT.DINV.WD.GD.ZS,EG.ELC.ACCS.ZS,EG.FEC.RNEW.ZS,EN.ATM.CO2E.KD.GD,EN.ATM.CO2E.KT,EN.ATM.CO2E.PC,EN.ATM.CO2E.PP.GD,EN.ATM.CO2E.PP.GD.KD,EN.ATM.GHGT.KT.CE,EN.ATM.METH.KT.CE,EN.ATM.NOXE.KT.CE,EN.URB.MCTY.TL.ZS,NV.AGR.TOTL.ZS,SE.PRM.CMPT.ZS,SH.DYN.MORT,SP.POP.GROW,SP.POP.TOTL,SP.URB.GROW,SP.URB.TOTL,SP.URB.TOTL.IN.ZS
51,2011,301038.000,67.451938,17.485548,56765.94,12.719234,1614.4,2.487275,93.446434,11.880000,0.677687,55939.998627,1.700113,0.250497,0.276731,75750.000000,11010.000229,8440.000000,21.648299,13.119988,89.361572,29.5,1.342666,32903699.0,2.308378,19275316.0,58.581
52,2012,304030.000,68.122339,18.030473,56786.18,12.723769,1016.6,2.892094,94.210518,10.930000,0.683052,58080.001831,1.741416,0.256850,0.278922,77550.003052,11100.000381,8000.000000,21.642350,12.329560,98.019630,27.8,1.353772,33352169.0,2.306865,19725140.0,59.142
53,2013,305850.000,68.530137,18.211965,56806.42,12.728304,1828.3,3.146164,97.199997,11.590000,0.647904,57590.000153,1.703668,0.243335,0.264570,78040.000916,11289.999962,8770.000000,21.639547,13.389567,96.023102,26.3,1.344234,33803527.0,2.283304,20180706.0,59.700
54,2014,300825.000,67.404212,17.031369,56826.66,12.732839,1454.3,2.959241,91.599998,11.140000,0.554636,58689.998627,1.713646,0.236404,0.226484,79239.997864,11479.999542,8670.000000,21.646865,10.353147,96.308159,24.9,1.308063,34248603.0,2.235073,20636838.0,60.256
55,2015,300470.000,67.324670,16.798790,56846.90,12.737374,2140.7,2.946097,97.300003,11.250000,0.547121,60409.999847,1.741903,0.223932,0.223415,81459.999084,11550.000191,9090.000000,21.668047,11.796193,96.257713,23.5,1.253058,34680458.0,2.166626,21088840.0,60.809
56,2016,308750.000,69.179924,18.420345,56997.90,12.771208,936.0,1.930010,97.800003,11.060000,0.543473,60319.999695,1.718163,0.220170,0.221926,80260.002136,11670.000076,7830.000000,21.697709,10.321965,95.042038,22.3,1.223170,35107264.0,2.125203,21541817.0,61.360
57,2017,310465.482,69.564302,18.863453,57115.90,12.797647,1757.6,2.260922,100.000000,10.450000,0.544752,63520.000458,1.787880,0.222448,0.222448,84989.997864,11770.000458,9210.000000,21.736284,11.160289,92.929527,21.2,1.191629,35528115.0,2.080754,21994745.0,61.908
58,2018,305258.072,68.397507,17.593931,57215.90,12.820054,2263.6,2.783379,98.099998,10.900000,0.540531,64959.999084,1.808085,0.215574,0.220724,86809.997559,11970.000267,9370.000000,21.793043,11.305540,93.597458,20.3,1.117897,35927511.0,1.994383,22437808.0,62.453
59,2019,296119.070,66.349780,15.458131,57320.90,12.843581,1454.1,1.334801,99.599998,10.690000,0.578071,71480.003357,1.968907,0.226494,0.236054,93080.001831,12159.999847,8890.000000,21.874308,10.842402,97.135727,19.5,1.043584,36304408.0,1.906108,22869599.0,62.994
60,2020,303820.000,68.075286,17.138696,57424.90,12.866883,742.9,1.169126,100.000000,11.098889,0.590803,61221.111298,1.764865,0.232856,0.241253,81908.888923,11555.555662,8696.666667,21.966290,10.664177,100.088120,18.7,1.053160,36688772.0,1.903584,23309111.0,63.532

In [25]:
climate.to_csv('../../Data/climate-change_prepared.csv', index=False)